/*
 * @(#)lmslabels_en.js 1.3  2009-09-02
 *
 * Copyright (c) 2003-2009 Werner Randelshofer
 * Hausmatt 10, Immensee, CH-6405, Switzerland
 * All rights reserved.
 *
 * The copyright of this software is owned by Werner Randelshofer. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Werner Randelshofer. For details see accompanying license terms. 
 */

/**
 * This file contains locale dependent labels for TinyLMS.
 * This is the set of English labels. Language code "en".
 *
 * IMPORTANT! This file MUST be plain ASCII except for the lines which are
 * marked with UTF-8.
 * All non-ASCII characters MUST be encoded using HEXADECIMAL HTML entities.
 * Other encodings are not supported and will lead into incorrect display of the
 * labels.
 * The lines which are marked with UTF-8 must be encoded with UTF-8. These lines
 * MUST not use HTML entities.
 *
 * This file is intended to be included in the top level frameset of an 
 * eLearning course generated by TinyLMS.
 *
 * Example:
 * <html>
 *   <head>
 *     <title>Learning Management System</title>
 *     <script language="JavaScript" src="tinylms/lib/collections.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="tinylms/lib/lmslabels.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="tinylms/lib/lmslabels_en.js" type="text/JavaScript"></script>
 *   </head>
 * </html>
 */
API.labels = new Map();
API.labels.importFromArray([
["debug.switchLoggingOn","Turn Logging On"],
["debug.switchLoggingOff","Turn Logging Off"],
["debug.showInfo","Show Info"],
["login.url",'tinylms/lmslogin_en.html'],
["login.title","Welcome"],
["login.welcome","Welcome to TinyLMS."],
["login.please","Please enter your user name."],
["login.userid","User Name:"],
["login.login","Login"],
["login.baduserid","Please verify your user id."], // UTF-8
["login.badpassword","Please verify your password."], // UTF-8
["statistics.title","Statistics"],
["statistics.pages","Page"],
["statistics.viewed","Viewed"],
["statistics.passed","Passed"],
["statistics.pagesvisited","You have visited {0} of {1} pages."],
["statistics.pagesfailed","You failed {0} exercises."],
["statistics.reset","Reset"],
["toc.logoff","Logout"],
["toc.index","Index"],
["toc.previous","Previous"],
["toc.next","Next"],
["toc.expandAll","Expand All"],
["toc.collapseAll","Collapse All"],
["quiz.title","{0} Random Questions"],
["quiz.quizmode.title","Quiz Mode"],
["quiz.coursemode.title","Course Mode"],
["quiz.results.title","Results"],
["quiz.results.summary","You have correclty answered {0} out of {1} randomly chosen questions."]
]);