/*
 * @(#)lmslabels_sl.js 1.3  2009-09-02
 *
 * Copyright (c) 2006-2009 Werner Randelshofer
 * Hausmatt 10, Immensee, CH-6405, Switzerland
 * All rights reserved.
 *
 * The copyright of this software is owned by Werner Randelshofer. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Werner Randelshofer. For details see accompanying license terms. 
 *
 * Slovenian translation by Sasa Divjak
 */

/**
 * This file contains locale dependent labels for TinyLMS.
 * This is the set of Slovenian labels. Language code "sl".
 *
 * IMPORTANT! This file MUST be plain ASCII except for the lines which are
 * marked with UTF-8.
 * All non-ASCII characters MUST be encoded using HEXADECIMAL HTML entities.
 * Other encodings are not supported and will lead into incorrect display of the
 * labels.
 * The lines which are marked with UTF-8 must be encoded with UTF-8. These lines
 * MUST not use HTML entities.
 *
 * This file is intended to be included in the top level frameset of an 
 * eLearning course generated by TinyLMS.
 *
 * Example:
 * <html>
 *   <head>
 *     <title>Learning Management System</title>
 *     <script language="JavaScript" src="tinylms/lib/collections.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="tinylms/lib/lmslabels.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="tinylms/lib/lmslabels_en.js" type="text/JavaScript"></script>
 *   </head>
 * </html>
 */
API.labels = new Map();
API.labels.importFromArray([
["debug.switchLoggingOn","Vklop izpisovanja"],
["debug.switchLoggingOff","Izklop izpisovanja"],
["debug.showInfo","Prikaz podatkov"],
["login.url",'tinylms/lmslogin_en.html'],
["login.title","Dobrodo&#x0161;el"],
["login.welcome","Dobrodo&#x0161;el v TinyLMS."],
["login.please","Vnesi svoje uporabni&#x0161;ko ime."],
["login.userid","Uporabni&#x0161;ko ime:"],
["login.login","Prijava"],
["login.baduserid","Preveri svoje uporabni\u0161ki ime."], // UTF-8
["login.badpassword","Preveri svoje geslo."], // UTF-8
["statistics.title","Statistika"],
["statistics.pages","Stran"],
["statistics.viewed","Gledano"],
["statistics.passed","Opravljeno"],
["statistics.pagesvisited","Obiskal si {0} od {1} strani."],
["statistics.pagesfailed","Nisi izpolnil {0} vaj."],
["statistics.reset","Reset"],
["toc.logoff","Odjava"],
["toc.index","Indeks"],
["toc.previous","Predhodnji"],
["toc.next","Naslednji"],
["toc.expandAll","Expand All"],
["toc.collapseAll","Collapse All"],
["quiz.title","{0} Random Questions"],
["quiz.quizmode.title","Quiz Mode"],
["quiz.coursemode.title","Course Mode"],
["quiz.results.title","Results"],
["quiz.results.summary","You have passed {0} out of {1} randomly chosen questions."]
]);
