/*
 * @(#)lmstreenav.js  1.0  2006-05-21
 *
 * Copyright (c) 2006 Werner Randelshofer
 * Hausmatt 10, Immensee, CH-6405, Switzerland
 * All rights reserved.
 *
 * The copyright of this software is owned by Werner Randelshofer. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Werner Randelshofer. For details see accompanying license terms. 
 */ 
/**
 * This scripts inserts a horizontal navigation bar at the current location
 * into a HTML document.
 *
 * This file is intended to be included in the body of a HTML document. The
 * HTML document must be in a child frame of the Learning Management System
 * generated by TinyLMS.
 *
 * Example:
 * <html>
 *   <head>
 *     <title>Table Of Contents</title>
 *     <script language="JavaScript" src="lib/lmscollections.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="lib/lmsstub.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="lib/lmstreenav.js" type="text/JavaScript"></script>
 *   </head>
 *   <body>
 *     <script language="JavaScript" type="text/JavaScript">nav.writeButtons()</script>
 *   </body>
 * </html>
 *
 * @version 1.0 2006-05-21 Created.
 */


Nav.prototype.gotoPreviousItem = function() {
	var api = stub.getAPI();
  	api.gotoPreviousItem();
}

Nav.prototype.gotoNextItem = function() {
	var api = stub.getAPI();
  	api.gotoNextItem();
}

Nav.prototype.writeButtons = function() {
	var api = stub.getAPI();
	if (api.isLoggedIn() && api.mode == api.MODE_COURSE) {
		var buttonClass = (api.isFirstItem(api.getCurrentItem())) ? "navButtonDisabled" : "navButton";
		document.writeln('<a class="'+buttonClass+'" href="#" onclick="nav.gotoPreviousItem()">'+api.labels.get('toc.previous')+'</a>');
		document.writeln('&nbsp;&nbsp;');
		buttonClass = (api.isLastItem(api.getCurrentItem())) ? "navButtonDisabled" : "navButton";
		document.writeln('<a class="'+buttonClass+'" href="#" onclick="nav.gotoNextItem()">'+api.labels.get('toc.next')+'</a>');
	}
}

function Nav() {
}

var nav = new Nav();
